#!/bin/bash
#Remove/hide terminal history, while keeping scrollback
clear -x

#Display ASCII art
echo "
                        ██    ██    ██                            
                          ██  ██      ██                          
                          ██    ██    ██                          
                                                                  
                      ████████████████████                        
                      ██                ████████                    
                      ██                ██    ▓▓                    
                      ██                ██    ██                    
                      ██                ████████                    
                        ██            ██                          
                    ████████████████████████                      
                    ██                    ▓▓                      
                      ████████████████████   Out for coffee, back in 5"

#Display Stopwatch, showing time gone. 
start=$(date +%s)
while true; do
    time="$(($(date +%s) - $start))"
    printf '%s\r' "		      Time passed: $(date -u -d "@$time" +%H:%M:%S)"
	
#Sleep to avoid CPU spam
	sleep 0.1
done
